"""Small dependency contracts used by the Nexus runtime."""

from __future__ import annotations

from collections.abc import Awaitable, Callable, Sequence
from typing import Any, Protocol

import numpy as np


class LLMService(Protocol):
    async def generate(self, prompt: str, **kwargs: Any) -> Any: ...
    async def close(self) -> None: ...


class STTService(Protocol):
    async def load_model(self) -> None: ...
    async def unload_model(self) -> None: ...
    async def transcribe(self, audio: np.ndarray, **kwargs: Any) -> Any: ...


class TTSService(Protocol):
    async def load_model(self) -> None: ...
    async def unload_model(self) -> None: ...
    async def speak(self, text: str, playback: Any) -> Any: ...


class CaptureService(Protocol):
    on_speech_start: Callable[[], None] | None
    on_speech_end: Callable[[], None] | None

    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def get_speech_buffer(self) -> np.ndarray | None: ...


class PlaybackService(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


class MemoryService(Protocol):
    def add(self, text: str, **kwargs: Any) -> Any: ...
    def search(self, query: str, *, limit: int = 5) -> Sequence[Any]: ...


EventCallback = Callable[[Any], None]
TaskScheduler = Callable[[Awaitable[Any]], Any]
